### ISSUE TITLE
RuntimeError: Negative discriminant in time marcher quadratic.

### ISSUE THREAD

**Issue by vince2003** [syshin1014/VGN#2]
Hi Seung Yeon Shin,
Thank you for your source code. However, I meet error as the following: "RuntimeError: Negative discriminant in time marcher quadratic." can you help me to fix the error?
Thank you!

**Comment by syshin1014** [comment]
Hi,
That error seems to be from the module 'scikit-fmm' and I can't point out what the exact problem is only from the error statement.
Actually, I haven't seen it before when I was developing my code.
Have you checked the inputs for 'skfmm.travel_time'?

**Comment by vince2003** [comment]
Hi Seung Yeon Shin,
Thank you for your reply. I have fixed this error. Furthermore, your environment uses Tensorflow 1.12. However, it can not run. I use Tensorflow 1.08 instead of 1.12. It is ok!
Thank you!

**Comment by Ihsan149** [comment]
@vince2003 how you fixed this error "Negative discriminant in time marcher quadratic."?
