### ISSUE TITLE
How to create the data files?

### ISSUE THREAD

**Issue by ycwu1997** [syshin1014/VGN#6]
Nice work. Thanks for your sharing.

I want to know how I can generate the data.txt (e.g. train.txt) file from the original retinal images for training or testing. Could you please give me some further information?

**Comment by syshin1014** [comment]
Hi, You can check https://github.com/syshin1014/VGN/issues/3 for that information.

**Comment by ycwu1997** [comment]
> Hi, You can check #3 for that information.

Thanks a lot
