### ISSUE TITLE
For checkpoint restoring

### ISSUE THREAD

**Issue by Ericforliu** [syshin1014/VGN#7]
![image](https://user-images.githubusercontent.com/40079490/92118622-4c561080-ee29-11ea-9068-d92c412000a7.png)
![image](https://user-images.githubusercontent.com/40079490/92118677-5d068680-ee29-11ea-93bf-967339bd7a91.png)
![image](https://user-images.githubusercontent.com/40079490/92118727-73acdd80-ee29-11ea-8c6a-c7b2aac63593.png)
Here are any problem when I want to restore the model you provide before.
Could you help me for this?

**Comment by bhupender-kaushal** [comment]
Hey @Ericforliu  could you find the issue underlying, i have been going thru this error, kindly jot down some updates if you hve them. Thanks.. :)
